name: SABnzbd
version: 98e7fb6
slug: sabnzbd
description: Free and easy binary newsreader
url: https://github.com/hassio-addons/addon-sabnzbd/tree/main/README.md
ingress: true
ingress_entry: sabnzbd/
panel_icon: mdi:arrow-down-bold
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8080/tcp: null
image: ghcr.io/hassio-addons/sabnzbd/{arch}
