arch:
- aarch64
- amd64
- armv7
description: Cloud native metrics
hassio_api: true
homeassistant_api: true
image: ghcr.io/hassio-addons/prometheus/{arch}
ingress: true
ingress_entry: graph
ingress_port: 9090
map:
- share:rw
name: Prometheus
panel_icon: mdi:chart-timeline
panel_title: Prometheus
ports:
  9090/tcp: null
ports_description:
  9090/tcp: Not required for Ingress
slug: prometheus
startup: services
url: https://github.com/hassio-addons/addon-prometheus
version: c1abdb4
