name: SQLite Web
version: 2e334c8
slug: sqlite-web
description: Explore your SQLite database
url: https://github.com/hassio-addons/addon-sqlite-web/tree/main/README.md
ingress: true
advanced: true
init: false
panel_icon: mdi:database
arch:
- aarch64
- amd64
- armv7
map:
- homeassistant_config:rw
- share:rw
schema:
  database: str?
image: ghcr.io/hassio-addons/sqlite-web/{arch}
