arch:
- aarch64
- amd64
- armhf
- armv7
- i386
audio: true
auth_api: true
description: A network based LED effect controller with support for advanced real-time
  audio effects!
hassio_api: true
image: ghcr.io/hassio-addons/ledfx/{arch}
map:
- ssl
name: ledfx
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
ports:
  80/tcp: 5333
ports_description:
  80/tcp: Web interface
schema:
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
slug: ledfx
url: https://github.com/hassio-addons/addon-ledfx
version: 92bb713
webui: '[PROTO:ssl]://[HOST]:[PORT:80]'
